# ===================================================================
# Generated on 2025-11-14
# This script recreates outbound Veeam related Windows Firewall rules exported
# from a fresh Veeam 12.3.2.4165. Run in elevated PowerShell.
# Example: Set-ExecutionPolicy -ExecutionPolicy Remotesigned -Scope Process -Force; .\Recreate-VeeamOutboundFirewallRules.ps1
# ===================================================================
[CmdletBinding()] param()

Write-Host 'Recreating outbound firewall rules...' -ForegroundColor Cyan

New-NetFirewallRule -DisplayName:'Veeam Catalog Service (Out)' -Description:'Outbound rule for Veeam Catalog Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup Catalog\Veeam.Backup.CatalogDataService.exe' -Protocol:TCP -LocalPort:9393 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Data Mover (Veeam Catalog Service)  (Out)' -Description:'Outbound rule for Veeam Data Mover included with Veeam Catalog Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup Catalog\WinAgent\VeeamAgent.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam VSS Hardware Provider Service (Out)' -Description:'Outbound rule for Veeam VSS Hardware Provider Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\VSS Hardware Provider\Veeam.VssHwSnapshotProvider.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Broker Service (Out)' -Description:'Outbound rule for Veeam Broker Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.BrokerService.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup CDP Coordinator Service (Out)' -Description:'Outbound rule for Veeam Backup CDP Coordinator Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.Cdp.Service.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup CDP Coordinator Service Communication (HTTPS) (Out)' -Description:'Outbound  rule for secure connections between Veeam Backup CDP Coordinator Service components' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:33035 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup CDP Coordinator Service Communication (Out)' -Description:'Outbound  rule for secure connections between Veeam Backup CDP Coordinator Service components' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:33034 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup Remote PowerShell Manager (Out)' -Description:'Outbound rule for Veeam Backup Remote PowerShell Manager' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.PSManager.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup Server RESTful API Service (Out)' -Description:'Outbound rule for Veeam Backup Server RESTful API Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:9419 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup UI Server (Out)' -Description:'Outbound rule for Veeam Backup UI Server' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.UIServer.exe' -Protocol:TCP -LocalPort:9396 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Data Mover (Out)' -Description:'Outbound rule for Veeam Data Mover included with Veeam Backup and Replication' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup\WinAgent\VeeamAgent.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Cloud Connect Service (Out)' -Description:'Outbound rule for Veeam Cloud Connect Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.CloudService.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup Management Service (Out)' -Description:'Outbound rule for Veeam Backup Management Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.Service.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup Secure Communication (Out)' -Description:'Outbound rule for secure connections between Veeam Backup & Replication components' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:9401 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Traffic Redirector (Out)' -Description:'Outbound rule for Veeam Traffic Redirector included with Veeam Backup & Replication' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Backup\VeeamNetworkRedirector.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup & Replication Console (Out)' -Description:'Outbound rule for Veeam Backup & Replication Console' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Console\veeam.backup.shell.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Traffic Redirector (Veeam Backup & Replication console) (Out)' -Description:'Outbound rule for Veeam Network Traffic included with Veeam Backup & Replication console' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup and Replication\Console\VeeamNetworkRedirector.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Installer Service (Veeam Backup and Replication) (Out)' -Description:'Outbound rule for Veeam Installer Service included with Veeam Backup and Replication' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Windows\Veeam\Backup\VeeamDeploymentSvc.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Distribution Service (Out)' -Description:'Outbound rule for Veeam Distribution Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Veeam Distribution Service\Veeam.Backup.Agent.ConfigurationService.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Backup VSS Integration Service (Out)' -Description:'Outbound rule for Veeam Backup VSS Integration Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Backup File System VSS Integration\VeeamFilesysVssSvc.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam vPower NFS Service (Out)' -Description:'Outbound rule for Veeam vPower NFS Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files (x86)\Veeam\vPowerNFS\VeeamNFSSvc.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Kubernetes Service (Out)' -Description:'Outbound rule for Veeam Kubernetes Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Plugins\Kasten\Service\Veeam.Backup.PlatformServices.Kasten.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam AHV Service (Out)' -Description:'Outbound rule for Veeam AHV Service.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Plugins\Nutanix AHV\Service\Veeam.AHV.Service.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam AHV UI (Out)' -Description:'Outbound rule for Veeam AHV UI.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:8543 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam KVM Service (Out)' -Description:'Outbound rule for Veeam KVM Service.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Plugins\RHV\Service\Veeam.RHV.Service.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam KVM UI (Out)' -Description:'Outbound rule for Veeam KVM UI.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:8544 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Proxmox VE Service (Out)' -Description:'Outbound rule for Veeam Proxmox VE Service.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Plugins\PVE\Service\Veeam.PVE.Service.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam PVE UI (Out)' -Description:'Outbound rule for Veeam PVE UI.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:8545 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam AWS Service (Out)' -Description:'Outbound rule for Veeam AWS Service.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Plugins\AWS\Service\Veeam.CloudBackup.PlatformService.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam AWS UI (Out)' -Description:'Outbound rule for Veeam AWS UI.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:9402 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Azure Service (Out)' -Description:'Outbound rule for Veeam for Azure Platform Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Plugins\Microsoft Azure\Service\Veeam.Azure.PlatformSvc.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Azure UI (Out)' -Description:'Outbound rule for Veeam Azure UI.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:20443 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam GCP Service (Out)' -Description:'Outbound rule for Veeam GCP Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Veeam\Plugins\GCP\Service\Veeam.GCP.PlatformService.WebService.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam GCP UI (Out)' -Description:'Outbound rule for Veeam GCP UI.' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Protocol:TCP -LocalPort:9403 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Mount Service (Out)' -Description:'Outbound rule for Veeam Mount Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files\Common Files\Veeam\Backup and Replication\Mount Service\Veeam.Backup.MountService.exe' -Protocol:TCP -LocalPort:6170 -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Guest Interaction Proxy (Out)' -Description:'Outbound rule for Veeam Guest Interaction Proxy' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files (x86)\Veeam\Backup Transport\GuestInteraction\Veeam.Guest.Interaction.Proxy.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Transport Service (Out)' -Description:'Outbound rule for Veeam Transport Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files (x86)\Veeam\Backup Transport\VeeamTransportSvc.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Data Mover x64 (Veeam Transport Service) (Out)' -Description:'Outbound rule for Veeam Data Mover x64 included with Veeam Transport Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files (x86)\Veeam\Backup Transport\x64\VeeamAgent.exe' -Protocol:TCP -InterfaceAlias:'Any'
New-NetFirewallRule -DisplayName:'Veeam Data Mover (Veeam Transport Service) (Out)' -Description:'Outbound rule for Veeam Data Mover included with Veeam Transport Service' -Group:'Veeam Networking' -Direction:Outbound -Action:Allow -Enabled:True -Program:'C:\Program Files (x86)\Veeam\Backup Transport\x86\VeeamAgent.exe' -Protocol:TCP -InterfaceAlias:'Any'

Write-Host 'Done.' -ForegroundColor Green
